server:
  port: 8080

spring:
  application:
    name: issueflow
  datasource:
    url: jdbc:postgresql://localhost:5432/issueflow
    username: issueflow
    password: issueflow
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
