-- Baseline schema for IssueFlow. Mirrors the DDL produced by Hibernate 6.6 for the
-- entity tree under com.att.tdp.issueflow so that spring.jpa.hibernate.ddl-auto=validate
-- finds no drift. Subsequent changes ship as V2__*.sql, V3__*.sql, ... .

create table users (
    id              bigint generated by default as identity,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    email           varchar(254) not null,
    full_name       varchar(120) not null,
    password_hash   varchar(100) not null,
    role            varchar(20)  not null check (role in ('ADMIN','DEVELOPER')),
    username        varchar(50)  not null,
    primary key (id)
);

create table projects (
    id              bigint generated by default as identity,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    deleted_at      timestamp(6) with time zone,
    description     varchar(2000),
    name            varchar(120) not null,
    owner_id        bigint       not null,
    primary key (id)
);

create table tickets (
    id              bigint generated by default as identity,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    deleted_at      timestamp(6) with time zone,
    description     varchar(10000),
    due_date        timestamp(6) with time zone,
    is_overdue      boolean      not null,
    priority        varchar(20)  not null check (priority in ('LOW','MEDIUM','HIGH','CRITICAL')),
    status          varchar(20)  not null check (status   in ('TODO','IN_PROGRESS','IN_REVIEW','DONE')),
    title           varchar(200) not null,
    type            varchar(20)  not null check (type     in ('BUG','FEATURE','TECHNICAL')),
    version         bigint       not null,
    assignee_id     bigint,
    project_id      bigint       not null,
    primary key (id)
);

create table comments (
    id              bigint generated by default as identity,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    content         varchar(5000) not null,
    version         bigint        not null,
    author_id       bigint        not null,
    ticket_id       bigint        not null,
    primary key (id)
);

create table comment_mentions (
    id                  bigint generated by default as identity,
    created_at          timestamp(6) with time zone not null,
    comment_id          bigint not null,
    mentioned_user_id   bigint not null,
    primary key (id)
);

create table ticket_dependencies (
    created_at              timestamp(6) with time zone not null,
    blocked_by_ticket_id    bigint not null,
    ticket_id               bigint not null,
    primary key (blocked_by_ticket_id, ticket_id)
);

create table attachments (
    id              bigint generated by default as identity,
    content_type    varchar(100) not null,
    data            bytea        not null,
    filename        varchar(255) not null,
    size_bytes      bigint       not null,
    uploaded_at     timestamp(6) with time zone not null,
    ticket_id       bigint       not null,
    uploaded_by     bigint,
    primary key (id)
);

create table audit_log (
    id              bigint generated by default as identity,
    action          varchar(20)  not null check (action      in ('CREATE','UPDATE','DELETE','RESTORE','AUTO_ASSIGN','AUTO_ESCALATE','LOGIN','LOGOUT')),
    actor           varchar(10)  not null check (actor       in ('USER','SYSTEM')),
    entity_id       bigint       not null,
    entity_type     varchar(20)  not null check (entity_type in ('USER','PROJECT','TICKET','COMMENT','DEPENDENCY','ATTACHMENT')),
    payload         text,
    performed_by    bigint,
    timestamp       timestamp(6) with time zone not null,
    primary key (id)
);

-- Unique constraints
alter table users            add constraint uk_users_username           unique (username);
alter table users            add constraint uk_users_email              unique (email);
alter table comment_mentions add constraint uk_mentions_comment_user    unique (comment_id, mentioned_user_id);

-- Indexes
create index ix_users_role            on users            (role);
create index ix_projects_owner        on projects         (owner_id);
create index ix_projects_deleted_at   on projects         (deleted_at);
create index ix_tickets_project       on tickets          (project_id);
create index ix_tickets_assignee      on tickets          (assignee_id);
create index ix_tickets_status        on tickets          (status);
create index ix_tickets_due_date      on tickets          (due_date);
create index ix_tickets_deleted_at    on tickets          (deleted_at);
create index ix_comments_ticket       on comments         (ticket_id);
create index ix_comments_author       on comments         (author_id);
create index ix_mentions_comment      on comment_mentions (comment_id);
create index ix_mentions_user         on comment_mentions (mentioned_user_id);
create index ix_deps_ticket           on ticket_dependencies (ticket_id);
create index ix_deps_blocker          on ticket_dependencies (blocked_by_ticket_id);
create index ix_attachments_ticket    on attachments      (ticket_id);
create index ix_audit_entity          on audit_log        (entity_type, entity_id);
create index ix_audit_timestamp       on audit_log        (timestamp);
create index ix_audit_performed_by    on audit_log        (performed_by);

-- Foreign keys
alter table projects            add constraint fk_projects_owner       foreign key (owner_id)             references users   (id);
alter table tickets             add constraint fk_tickets_project      foreign key (project_id)           references projects(id);
alter table tickets             add constraint fk_tickets_assignee     foreign key (assignee_id)          references users   (id);
alter table comments            add constraint fk_comments_ticket      foreign key (ticket_id)            references tickets (id);
alter table comments            add constraint fk_comments_author      foreign key (author_id)            references users   (id);
alter table comment_mentions    add constraint fk_mentions_comment     foreign key (comment_id)           references comments(id);
alter table comment_mentions    add constraint fk_mentions_user        foreign key (mentioned_user_id)    references users   (id);
alter table ticket_dependencies add constraint fk_deps_ticket          foreign key (ticket_id)            references tickets (id);
alter table ticket_dependencies add constraint fk_deps_blocker         foreign key (blocked_by_ticket_id) references tickets (id);
alter table attachments         add constraint fk_attachments_ticket   foreign key (ticket_id)            references tickets (id);
alter table attachments         add constraint fk_attachments_uploader foreign key (uploaded_by)          references users   (id);
